name: Deploy Sphinx Docs

on:
    workflow_dispatch:
    push:
        tags:
          - '*.*.*'

jobs:
    xml:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download Godot
              run: |
                wget -q "https://downloads.godotengine.org/?version=4.6.1&flavor=stable&slug=linux.x86_64.zip&platform=linux.64" -O godot.zip
                unzip -q godot.zip
                mv Godot_v4.6.1-stable_linux.x86_64 godot
                chmod +x godot
                echo "$(pwd)" >> $GITHUB_PATH
            
            - name: Verify Godot
              run: godot --version
            
            - name: Generate XML
              run: |
                godot --headless --path . --import
                godot --headless --path . --doctool xml --no-docbase --gdscript-docs res://addons/rpg_components_2d
                rm -f xml/addons--rpg_components_2d--rpg_components_2d.gd.xml
            
            - name: Upload generated XML
              uses: actions/upload-artifact@v4
              with:
                name: xml-export
                path: xml
                if-no-files-found: error
            
            - name: Get changes from CHANGELOG.md
              if: github.ref_type == 'tag'
              id: changes
              uses: MUmarShahbaz/get-changelog@v2
              with:
                version: ${{ github.ref_name }}
            
            - name: Create ZIP for Release
              if: github.ref_type == 'tag'
              run: cd ./addons && zip -r rpg_components_2d.zip rpg_components_2d
              
            - name: Create Release
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@v2
              with:
                files: addons/rpg_components_2d.zip
                name: "RPG Components 2D - ${{ github.ref_name }}"
                body: ${{ steps.changes.outputs.content }}
                draft: false
                prerelease: false

            
    rst:
        runs-on: ubuntu-latest
        needs: xml

        steps:
            - name: Checkout to Docs
              if: github.ref_type != 'tag'
              uses: actions/checkout@v4
              with:
                ref: docs

            - name: Download XML
              uses: actions/download-artifact@v4
              with:
                name: xml-export
                path: xml

            - name: Parse version
              id: version
              run: |
                if [ "${{ github.ref_type }}" != "tag" ]; then
                  echo "Not a tag. Extracting last version from conf.py..."
                  VERSION=$(sed -n "s/^release\s*=\s*['\"]\(.*\)['\"]/\1/p" conf.py)
                  
                  if [ -z "$VERSION" ]; then
                    echo "Error: Could not find previous release version in conf.py"
                    exit 1
                  fi
                else
                  echo "Triggered by a tag. Extracting version from tag name..."
                  VERSION="${GITHUB_REF_NAME}"
                fi

                echo "Version detected: $VERSION"

                IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

                echo "major=$MAJOR" >> "$GITHUB_OUTPUT"
                echo "minor=$MINOR" >> "$GITHUB_OUTPUT"
                echo "patch=$PATCH" >> "$GITHUB_OUTPUT"

            - name: Create RST
              id: make_rst
              uses: MUmarShahbaz/Godot-XML-to-RST@main
              with:
                short_name: rpg_components_2d
                name: RPG Components 2D
                major: ${{ steps.version.outputs.major }}
                minor: ${{ steps.version.outputs.minor }}
                patch: ${{ steps.version.outputs.patch }}
                status: stable
                built-in: true
                website: https://godotrpgcomponents.xyz
                xml: xml

            - name: Upload generated RST
              uses: actions/upload-artifact@v4
              with:
                name: rst-export
                path: ${{ steps.make_rst.outputs.path }}
                if-no-files-found: error

    sphinx:
      runs-on: ubuntu-latest
      needs: rst

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: docs
        
        - name: Update Version
          if: github.ref_type == 'tag'
          shell: python
          run: |
            import os
            import re
            tag_name = os.environ.get('GITHUB_REF_NAME')
            with open('conf.py', 'r', encoding='utf-8') as f:
                content = f.read()
            pattern = r"release\s*=\s*['\"].*?['\"]"
            replacement = f"release = '{tag_name}'"
            updated_content = re.sub(pattern, replacement, content)
            with open('conf.py', 'w', encoding='utf-8') as f:
                f.write(updated_content)

        - name: Commit and push
          if: github.ref_type == 'tag'
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add .
            git commit -m "Updated docs" || exit 0
            git push origin docs

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.14

        - name: Install Dependencies
          run: pip install sphinx sphinx_rtd_theme sphinxcontrib-mermaid sphinxext-opengraph sphinxext-opengraph[social_cards]
        
        - name: Download RST
          uses: actions/download-artifact@v4
          with:
            name: rst-export
        
        - name: Unzip RST Files and delete .zip
          run: |
            unzip -n converted.zip
            rm converted.zip
        
        - name: Generate Documentation with Sphinx
          run: make html && python meta_generator.py
        
        - name: Upload generated HTML
          uses: actions/upload-artifact@v4
          with:
            name: sphinx-export
            path: _build/html
            if-no-files-found: error

    deploy:
      runs-on: ubuntu-latest
      needs: sphinx

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: gh-pages
        
        - name: Clear All
          run: find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
        
        - name: Download Latest Build
          uses: actions/download-artifact@v4
          with:
            name: sphinx-export
        
        - name: Commit and push
          run: |
            echo "" > .nojekyll
            echo "godotrpgcomponents.xyz" > CNAME
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add .
            git commit -m "Updated docs" || exit 0
            git push origin gh-pages